# Generated by Django 5.2 on 2025-05-27 06:57

import django.db.models.deletion
import libraria.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewWeb',
            fields=[
                ('revw_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('review_field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='booklist',
            fields=[
                ('book_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=150)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('years', models.PositiveBigIntegerField()),
                ('synopsis', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_image', models.ImageField(upload_to='cover/')),
                ('stock', models.PositiveIntegerField()),
                ('librender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraria.category')),
            ],
        ),
        migrations.CreateModel(
            name='borrowing',
            fields=[
                ('borrowing_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=libraria.models.default_return_date)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Declined', 'Declined'), ('Finished', 'Finished'), ('FinePending', 'Fine Pending')], default='Pending', max_length=20)),
                ('denda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('fine_proof', models.ImageField(blank=True, null=True, upload_to='bukti_denda/')),
                ('is_fine_paid', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='libraria.booklist')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('signup', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='review_user',
            fields=[
                ('reviewuser_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
